<?php

declare(strict_types=1);

namespace Middag\Demo\Standalone\Http;

use Middag\Demo\Standalone\Domain\Eloquent\User;
use Middag\Demo\Standalone\Form\LoginForm;
use Middag\Demo\Standalone\Http\Concern\RendersPages;
use Middag\Framework\Form\Renderer\RendererRegistry;
use Middag\Framework\Http\Contract\AuthenticatorInterface;
use Middag\Framework\Http\Controller\AbstractController;
use Middag\Ui\Page\PageBuilder;
use Middag\Ui\Region\RegionBuilder;
use Middag\Ui\Shared\Enum\RenderTarget;
use Symfony\Component\HttpFoundation\Response;

/**
 * Demo login over the framework's OSS auth primitive (H3 shipped upstream):
 * verifies email + password_hash against `demo_users`, then establishes the
 * session via {@see AuthenticatorInterface::login()}. The authenticated record is
 * surfaced as the `auth` Inertia SharedProp; the kernel's `#[Auth]` gate (armed
 * by binding AuthenticatorInterface) protects the task UI.
 *
 * The login screen is emitted as a contract-driven form_panel; rendering it
 * needs a CUSTOM @middag-io/react login component (the lib ships none), which is
 * future `ui/` work — the backend (this controller + the contract) is complete.
 */
final class AuthController extends AbstractController
{
    use RendersPages;

    public function __construct(
        private readonly AuthenticatorInterface $auth,
        private readonly RendererRegistry $renderers,
        private readonly LoginForm $form,
    ) {}

    public function loginForm(): Response
    {
        // The form_panel schema is generated by the framework form pipeline (the
        // same AbstractForm → InertiaRenderer path the task form uses), not
        // hand-built: the renderer emits the canonical @middag-io/react
        // FormFieldNode shape, and middag-io/ui's RegionBuilder::formPanel wraps it.
        $rendered = $this->renderers->get(RenderTarget::PROPS)->render($this->form)->props;

        $contract = PageBuilder::page('demo.login')
            // Custom chromeless shell (registered host-side) — no app sidebar/nav
            // on the unauthenticated entry point. The form_panel still rides in the
            // `content` region (stack layout), centered by AuthShell.
            ->shell('auth')
            ->title('Sign in')
            ->subtitle('')
            ->region('content', function (RegionBuilder $region) use ($rendered): void {
                // submit/cancel labels + cancel target ride in form_panel meta (the
                // React FormPanelBlock reads data.meta.submitLabel/cancelLabel/cancelHref).
                // Cancel → /login reloads a clean form, so it reads as "Reset".
                $region->formPanel(
                    'login',
                    '/login',
                    'POST',
                    $rendered['schema'] ?? [],
                    $rendered['values'] ?? [],
                    null,
                    ['meta' => ['validation' => 'both', 'submitLabel' => 'Sign in', 'cancelLabel' => 'Reset', 'cancelHref' => '/login']],
                );
            })
            ->build();

        return $this->page($contract);
    }

    public function login(): Response
    {
        $payload = $this->request->getPayload();
        $email = (string) $payload->get('email', '');
        $password = (string) $payload->get('password', '');

        $user = User::findByEmail($email);

        if ($user === null || !$user->verifyPassword($password)) {
            $this->flash('error', 'Invalid credentials.');

            return $this->redirectToRoute('login.form');
        }

        // The single demo operator is the help-desk supervisor — the capability
        // opens the supervisor-only columns on /agents (the Can gate).
        $this->auth->login((int) $user->id, [
            'name' => (string) $user->name,
            'email' => (string) $user->email,
            'capabilities' => ['helpdesk:supervise'],
        ]);
        $this->flash('success', 'Welcome, ' . (string) $user->name . '.');

        return $this->redirectToRoute('dashboard.index');
    }

    public function logout(): Response
    {
        $this->auth->logout();
        $this->flash('info', 'Signed out.');

        return $this->redirectToRoute('login.form');
    }
}
